# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Employee Details' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Employee Details
    pod 'SDWebImage', '~> 5.0'

  target 'Employee DetailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Employee DetailsUITests' do
    # Pods for testing
  end

end
